server:
    port: 9191

spring:
    application:
        name: API-GATEWAY
    cloud: 
        gateway: 
            routes: 
                - id: USER-SERVICE
                  uri: lb://USER-SERVICE
                  predicates:
                    - Path=/users/**
                  filters:
                    - name: CircuitBreaker
                      args:
                        name: USER-SERVICE
                        fallbackuri: forward:/userServiceFallBack
                - id: DEPARTMENT-SERVICE
                  uri: lb://DEPARTMENT-SERVICE
                  predicates: 
                    - Path=/departments/**
                  filters:
                    - name: CircuitBreaker
                      args:
                        name: DEPARTMENT-SERVICE
                        fallbackuri: forward:/departmentServiceFallBack

# to return to fallback method in case microservices do not respond
hystrix:
    command:
        fallbackcmd:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 4000


# To showcase the information in Hystrix dashboard and hystrix.stream will point from the actuator
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

